[unstable]
build-std         = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-cosmic.json"

[target.x86_64-cosmic]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--no-rosegment",
]
