# CosmicOS — Limine Boot Configuration
# Cosmic v0.0.1 Developer Beta — Prestazioni spaziali

TIMEOUT=0
SERIAL=yes

:CosmicOS v0.0.1 Developer Beta
    COMMENT=Prestazioni spaziali
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/cosmic-kernel.elf
